[package]
name = "check-db"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "check-db"
path = "src/main.rs"

[dependencies]
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
