services:
  app:
    image: mcr.microsoft.com/devcontainers/rust:1
    volumes:
      - ..:/workspace
    command: sleep infinity
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://attendance_user:attendance_password@postgres:5432/attendance_dev
      TEST_DATABASE_URL: postgresql://attendance_user:attendance_password@postgres:5432/attendance_test

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: attendance_user
      POSTGRES_PASSWORD: attendance_password
      POSTGRES_DB: attendance_dev
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
